baseurl = "http://teste.tag.vc/noticias/"
paginate = 6
summaryLength = 7
DefaultContentLanguage = "pt"

title = "Not√≠cias"

[params.posts]
    showAuthor = true
    showDate = true
    showTags = true
    dateFormat = "Monday, Jan, 2006"
