baseurl = "https://www.afilio.com.br/noticias/"
paginate = 12
summaryLength = 7
DefaultContentLanguage = "pt"

title = "Not√≠cias"

[params.posts]
    showAuthor = true
    showDate = true
    showTags = true
    dateFormat = "02/01/2006"
