baseurl = "http://teste.tag.vc/noticias/"
paginate = 12
summaryLength = 7
DefaultContentLanguage = "pt"
title = "Not√≠cias"
disableKinds = ["taxonomyTerm", "taxonomy"]

[params]
    assetsUrl = "http://teste.tag.vc/"

[params.posts]
    showAuthor = true
    showDate = true
    showTags = true
    dateFormat = "02/01/2006"


    
